app:
  host: 'http://localhost'
  port: 3010

db:
  arangodb:
    urls:
    - 'http://localhost:8529'
    name: 'app_nest_dev'
    username: 'app_nest_dev'
    password: 'secret'
    certs: []

graphql:
  introspection: true
  playground: true
  subscriptions: false
  autoSchemaFile: true
  sortSchema: true
