http:
  host: 'http://localhost'
  port: 3000

db:
  arangodb:
    host: 'http://localhost'
    port: 8529
    name: 'app_nest_test'
    username: 'app_nest_test'
    password: 'secret'
    certs: []
